#!/usr/bin/env bash
# Transfers a file from our client to a server

# Example: scp path/filename ubuntu@54.84.27.133:/home/ubuntu
# Example2: scp -i ~/.ssh/id_rsa.pub path/filename ubuntu@54.84.27.133:/home/ubuntu
# The Example2 is use in the case of using a different ssh from the default

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
