#!/usr/env bash
# script that loops from 1 to 10,  bad luck at 4th, good luck at 8th then Best School

x=1

while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
		(( x++ ))
done
