#!/usr/bin/env bash
# configure ssh to connect to a server without typing a password

Host *
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnowHosts yes
	GSSAPIAuthentication yes
	GSSAIPDelegateCredentials no
